---
- hosts: swarmies
  name: GiAnt setup
  become: yes
  tasks:
    - name: Remove/Disable unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: absent
        
    - name: Update & Upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apt-utils 
          - build-essential 
          - glpk-utils 
          - openssh-server
          - python3-pip
          - python3-dev 
          - python3-lxml 
          - python3-pygame 
          - python3-wxgtk4.0 
          - python3-yaml
          - curl 
          - gnupg 
          - lsb-release
          - software-properties-common
          
    #- name: Adding universe repo
    #  ansible.builtin.command: sudo add-apt-repository universe # This causes a hang
      
    - name: Authorizing GPG key with apt
      become: true
      ansible.builtin.command: curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        
    - name: Create ros2.list file
      become: true
      file:
        path: /etc/apt/sources.list.d/ros2.list
        state: touch
        mode: 0644
        
    - name: Add repository to the source list
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/ros2.list
        line: "deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main"
        mode: 0644
    
    - name: Update & Upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        
    - name: Install packages ros-humble-desktop & etc.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes
        name:
          - ros-humble-desktop
          - python3-matplotlib 
          - python3-opencv 
          - python3-pip 
          - python3-rosinstall 
          - python3-rosinstall-generator 
          - python3-wstool 
          - ros-humble-usb-cam
          - ros-humble-image-view
          - python3-colcon-common-extensions
          - ipython3
          - python3-rosdep


    - name: Disable the x-server
      ansible.builtin.shell: sudo systemctl set-default multi-user #or use ansible.builtin.systemd?
      become: yes
      become_user: swarmie

    - name: Download & Untar Arduino
      ansible.builtin.unarchive:
        src: https://downloads.arduino.cc/arduino-1.8.19-linux64.tar.xz
        dest: /home/swarmie/SwarmieOS
        remote_src: yes
     
    - name: Append source noetic to bashrc
      become: true
      ansible.builtin.lineinfile:
        path: /home/swarmie/.bashrc
        line: "source /opt/ros/noetic/setup.bash"
        mode: 0644
      become: yes
      become_user: swarmie
      
    - name: Generate RSA SSH key
      ansible.builtin.shell: ssh-keygen #or use community.crypto.openssh_keypair?
      become: yes
      become_user: swarmie
      
    - name: Add the user swarmie to the dialout group
      ansible.builtin.user:
        name: swarmie
        group: dialout
        
    - name: Add the user swarmie to the video group
      ansible.builtin.user:
        name: swarmie
        group: video
    
    - name: Git clone BCLab-UNM's SwarmieOS
      ansible.builtin.git:
        repo: https://github.com/BCLab-UNM/SwarmieOS.git
        dest: /home/swarmie/SwarmieOS/
        update: yes
        version: humble
      become: yes
      become_user: swarmie

    - name: Remove build directory
      ansible.builtin.file:
        path: /home/swarmie/SwarmieOS/build
        state: absent

    - name: Remove install directory
      ansible.builtin.file:
        path: /home/swarmie/SwarmieOS/install
        state: absent
      
    - name: Building SwarmieOS with colcon build continue-on-error & symlink
      ansible.builtin.shell: source /opt/ros/humble/setup.bash && colcon build --continue-on-error --symlink-install
      args:
        chdir: /home/swarmie/SwarmieOS/
        executable: /bin/bash
      become: yes
      become_user: swarmie

    - name: All done rebooting the GiANT
      reboot:

